version: '3.8'

services:
    hubot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /scripst:/home/hubot/scripst
        ports:
            - 5090:8080
